#!/bin/bash
[[ ${CONFIG} ]] && CONFIG=$(printf "%q\n" "$(realpath "${CONFIG}")")
export PATH="${PATH}:/usr/lib/java-ebuilder/bin"
export EROOT=$(dirname /etc)

if [[ $# -gt 0 ]]; then
    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
        echo This is a helper to automagically generate ebuild for 
        echo Maven artifacts defined in ${EROOT}/etc/java-ebuilder.conf
        echo
        echo Usage: movl [options] [target] ...
        echo Options: please refer to \`make -h\`
        echo Targets:
        echo "  all                alias for stage2 and post-stage2"
        echo "  build              alias for stage2 and post-stage2"
        echo "  stage1             resolve the dependency graph of the provided Maven artifact"
        echo "  stage2             generate ebuild files of the whole dep graph"
        echo "  force-stage2       force generate stage2 ebuild files"
        echo "  post-stage2        generate digests for ebuilds"
        echo "  clean-cache        remove cache files"
        echo "  clean-stage1       remove stage1-related stuffs"
        echo "  clean-stage2       remove stage2-related stuffs"
        echo "  clean              remove all the generated stuffs"
        echo "Bash Variables:"
        echo "  CONFIG             path to the config file"
        echo "                     default: ${EROOT}/etc/java-ebuilder.conf"
        echo "  DEFAULT_CATEGORY   the default category of the generated ebuilds"
        echo "                     default: app-maven"
        echo "  MAVEN_NODEP        set this variable to stop tree.sh from recursively resolving"
        echo "                     the dependencies of MAVEN_ARTS"
        echo "  REPOSITORY         where to find the pom and jar files"
        echo "                     default: https://repo1.maven.org/maven2"
        echo "  TSH_NODEBUG        set this variable to make \`movl build\` more silent"
        exit
    fi
else
    movl -h
    exit 0
fi

cd "${EROOT}/usr/lib/java-ebuilder/Makefiles"
make $@

